"""
EWMA drift detector — double exponential moving average.

Detects gradual drift by comparing a fast EWMA (short memory) against a slow
EWMA (long memory). Complements ZScoreDetector: ZScore catches sudden spikes;
this detector catches slow shifts that Welford's running mean absorbs over time.

Mirrors FovetDrift in edge-core/include/fovet/drift.h so that calibrated
parameters can be exported and loaded directly on the ESP32.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from forge.config import EWMADriftDetectorConfig
from forge.data.base import Dataset
from forge.detectors.base import Detector, DetectionResult

_C_HEADER_TEMPLATE = """\
/*
 * Fovet SDK — Sentinelle
 * Auto-generated by Fovet Forge. DO NOT EDIT.
 *
 * EWMA drift calibration for pipeline: {pipeline_name}
 * Calibrated on {n_samples} samples, {n_features} feature(s): {columns}
 * Threshold: {threshold:.6f} (auto-calibrated at {threshold_percentile}th percentile)
 */
#ifndef FOVET_DRIFT_CONFIG_H
#define FOVET_DRIFT_CONFIG_H

#include "fovet/drift.h"

/* One FovetDrift context per feature channel.
 * Pass the matching struct to fovet_drift_update() in your HAL loop. */
{contexts}
#endif /* FOVET_DRIFT_CONFIG_H */
"""

_CONTEXT_TEMPLATE = """\
/* Feature: {column} — alpha_fast={alpha_fast:.4f}, alpha_slow={alpha_slow:.4f}, threshold={threshold:.6f} */
static FovetDrift fovet_drift_{safe_col} = {{
    .ewma_fast  = {ewma_fast:.6f}f,
    .ewma_slow  = {ewma_slow:.6f}f,
    .alpha_fast = {alpha_fast:.6f}f,
    .alpha_slow = {alpha_slow:.6f}f,
    .threshold  = {threshold:.6f}f,
    .count      = {count}U,
}};"""


@dataclass
class _FeatureState:
    ewma_fast: float
    ewma_slow: float
    count: int


class EWMADriftDetector(Detector):
    """EWMA drift detector — double exponential moving average.

    Detects gradual drift by comparing a fast EWMA (short memory) against a
    slow EWMA (long memory). For multi-feature datasets, the anomaly score is
    the maximum drift magnitude across all feature channels.

    Threshold auto-calibration:
        - Run both EWMAs through training data.
        - Collect all |ewma_fast - ewma_slow| values.
        - Set threshold = percentile(magnitudes, threshold_percentile).
        - This captures typical variance and flags only genuine drifts.

    To override auto-calibration, set ``threshold`` explicitly in the config.
    """

    def __init__(self, config: EWMADriftDetectorConfig) -> None:
        self.config = config
        self._alpha_fast: float = config.alpha_fast
        self._alpha_slow: float = config.alpha_slow
        self._threshold: float | None = None
        self._post_fit_states: list[_FeatureState] = []
        self._columns: list[str] = []
        self._n_samples: int = 0

    # ------------------------------------------------------------------
    # Fit
    # ------------------------------------------------------------------

    def fit(self, dataset: Dataset) -> None:
        """Run EWMAs through training data and auto-calibrate threshold."""
        X = dataset.samples.astype(np.float64)
        n, n_features = X.shape
        self._columns = list(dataset.columns)
        self._n_samples = n

        alpha_f = self._alpha_fast
        alpha_s = self._alpha_slow

        all_magnitudes: list[float] = []
        self._post_fit_states = []

        for feat_idx in range(n_features):
            col = X[:, feat_idx]
            # Seed both EWMAs with the first sample (no drift on first sample)
            ewma_f = float(col[0])
            ewma_s = float(col[0])
            count = 1

            magnitudes: list[float] = []
            for i in range(1, n):
                ewma_f = alpha_f * col[i] + (1.0 - alpha_f) * ewma_f
                ewma_s = alpha_s * col[i] + (1.0 - alpha_s) * ewma_s
                count += 1
                magnitudes.append(abs(ewma_f - ewma_s))

            all_magnitudes.extend(magnitudes)
            self._post_fit_states.append(
                _FeatureState(ewma_fast=ewma_f, ewma_slow=ewma_s, count=count)
            )

        # Threshold: explicit config value or auto-calibrated from percentile
        if self.config.threshold is not None:
            self._threshold = self.config.threshold
        else:
            arr = np.array(all_magnitudes, dtype=np.float64)
            self._threshold = float(np.percentile(arr, self.config.threshold_percentile))
            # Guard against degenerate signals (constant / nearly constant)
            if self._threshold < 1e-9:
                self._threshold = max(float(arr.std() * 3.0), 1e-3)

    # ------------------------------------------------------------------
    # Score / predict
    # ------------------------------------------------------------------

    def _check_fitted(self) -> None:
        if not self._post_fit_states:
            raise RuntimeError("EWMADriftDetector must be fitted before scoring.")

    def score(self, dataset: Dataset) -> np.ndarray:
        """Return max drift magnitude across features for each sample.

        EWMAs continue from the post-fit state so that test-set scores
        reflect real sequential behaviour (no look-ahead).
        """
        self._check_fitted()
        X = dataset.samples.astype(np.float64)
        n, n_features = X.shape

        alpha_f = self._alpha_fast
        alpha_s = self._alpha_slow

        per_feature = np.zeros((n, n_features), dtype=np.float64)

        for feat_idx in range(n_features):
            state = self._post_fit_states[feat_idx]
            ewma_f = state.ewma_fast
            ewma_s = state.ewma_slow
            col = X[:, feat_idx]
            for i in range(n):
                ewma_f = alpha_f * col[i] + (1.0 - alpha_f) * ewma_f
                ewma_s = alpha_s * col[i] + (1.0 - alpha_s) * ewma_s
                per_feature[i, feat_idx] = abs(ewma_f - ewma_s)

        return per_feature.max(axis=1).astype(np.float32)

    def predict(self, dataset: Dataset) -> DetectionResult:
        scores = self.score(dataset)
        threshold = self._threshold
        labels = (scores >= threshold).astype(np.int8)
        return DetectionResult(
            scores=scores,
            labels=labels,
            threshold=threshold,
            detector_name="ewma_drift",
        )

    # ------------------------------------------------------------------
    # Export — fovet_drift_config.h + drift_config.json
    # ------------------------------------------------------------------

    def export(self, output_dir: Path, stem: str, **_kwargs) -> list[Path]:
        """Write fovet_drift_config.h and drift_config.json."""
        self._check_fitted()
        output_dir.mkdir(parents=True, exist_ok=True)

        paths: list[Path] = []

        # C header
        contexts = []
        for col, state in zip(self._columns, self._post_fit_states):
            safe_col = col.replace(" ", "_").replace("-", "_")
            contexts.append(
                _CONTEXT_TEMPLATE.format(
                    column=col,
                    safe_col=safe_col,
                    alpha_fast=self._alpha_fast,
                    alpha_slow=self._alpha_slow,
                    threshold=self._threshold,
                    ewma_fast=state.ewma_fast,
                    ewma_slow=state.ewma_slow,
                    count=state.count,
                )
            )

        header = _C_HEADER_TEMPLATE.format(
            pipeline_name=stem,
            n_samples=self._n_samples,
            n_features=len(self._columns),
            columns=", ".join(self._columns),
            threshold=self._threshold,
            threshold_percentile=self.config.threshold_percentile,
            contexts="\n\n".join(contexts),
        )

        h_path = output_dir / "fovet_drift_config.h"
        h_path.write_text(header, encoding="utf-8")
        paths.append(h_path)

        # JSON config
        json_data = {
            "pipeline": stem,
            "detector": "ewma_drift",
            "alpha_fast": self._alpha_fast,
            "alpha_slow": self._alpha_slow,
            "threshold": self._threshold,
            "threshold_percentile": self.config.threshold_percentile,
            "features": self._columns,
            "n_training_samples": self._n_samples,
            "post_fit_states": [
                {
                    "feature": col,
                    "ewma_fast": state.ewma_fast,
                    "ewma_slow": state.ewma_slow,
                    "count": state.count,
                }
                for col, state in zip(self._columns, self._post_fit_states)
            ],
        }

        j_path = output_dir / "drift_config.json"
        j_path.write_text(json.dumps(json_data, indent=2), encoding="utf-8")
        paths.append(j_path)

        return paths
