"""
MAD (Median Absolute Deviation) anomaly detector.

Robust, outlier-resistant streaming detector using a fixed-size ring buffer.
Score = |x - median| / (1.4826 * MAD).  The 1.4826 consistency constant makes
the score approximately equal to the number of sigma for Gaussian data.

Mirrors FovetMAD in edge-core/include/fovet/mad.h so that calibrated parameters
(window seed + threshold) can be exported and loaded directly on the ESP32.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from forge.config import MADDetectorConfig
from forge.data.base import Dataset
from forge.detectors.base import Detector, DetectionResult

# FOVET_MAD_MAX_WINDOW compile-time cap — must match mad.h
_FOVET_MAD_MAX_WINDOW = 128

_C_HEADER_TEMPLATE = """\
/*
 * Fovet SDK — Sentinelle
 * Auto-generated by Fovet Forge. DO NOT EDIT.
 *
 * MAD detector calibration for pipeline: {pipeline_name}
 * Calibrated on {n_samples} samples, {n_features} feature(s): {columns}
 * Window size: {win_size}, Threshold: {threshold:.6f} (auto-calibrated at {threshold_percentile}th percentile)
 */
#ifndef FOVET_MAD_CONFIG_H
#define FOVET_MAD_CONFIG_H

#include "fovet/mad.h"

/* One FovetMAD context per feature channel.
 * Pass the matching struct to fovet_mad_update() in your HAL loop. */
{contexts}
#endif /* FOVET_MAD_CONFIG_H */
"""

_CONTEXT_TEMPLATE = """\
/* Feature: {column} — win_size={win_size}, threshold_mad={threshold:.6f} */
static FovetMAD fovet_mad_{safe_col} = {{
    .window        = {{{window_values}}},
    .scratch       = {{0}},
    .head          = 0U,
    .count         = {win_size}U,
    .win_size      = {win_size}U,
    .threshold_mad = {threshold:.6f}f,
}};"""


def _mad_score(value: float, window: np.ndarray) -> float:
    """Compute MAD anomaly score for a value against a window of samples.

    Matches the C99 fovet_mad_score() implementation exactly.
    """
    med = float(np.median(window))
    mad = float(np.median(np.abs(window - med)))
    deviation = abs(value - med)
    if mad < 1e-9:
        return 0.0 if deviation < 1e-9 else 1e9
    return deviation / (1.4826 * mad)


def _rolling_scores(col: np.ndarray, win_size: int, seed: np.ndarray | None = None) -> np.ndarray:
    """Compute MAD scores for a 1-D array using a rolling ring buffer.

    Mirrors fovet_mad_update(): each sample is scored against the *current*
    window (the previous win_size samples) BEFORE being added to the buffer.
    Samples during warm-up (before the buffer fills) receive score 0.

    Args:
        col:      1-D float array of samples.
        win_size: Ring buffer size.
        seed:     Optional 1-D array of up to win_size pre-training samples
                  used to pre-seed the ring buffer (enables continuity between
                  fit and score on sequential data).
    """
    n = len(col)
    scores = np.zeros(n, dtype=np.float64)

    # Pre-seed ring buffer from training tail
    if seed is not None and len(seed) > 0:
        buf = list(seed[-win_size:])
    else:
        buf = []

    for i in range(n):
        if len(buf) >= win_size:
            window = np.array(buf[-win_size:], dtype=np.float64)
            scores[i] = _mad_score(float(col[i]), window)
        # Add sample to buffer (mirrors writing to ring buffer after scoring)
        buf.append(float(col[i]))

    return scores


class MADDetector(Detector):
    """MAD (Median Absolute Deviation) streaming anomaly detector.

    For multi-feature datasets, the anomaly score is the maximum MAD score
    across all feature channels (consistent with EWMA drift / Z-Score).

    Threshold auto-calibration:
        - Score every sample after warm-up on training data.
        - Set threshold = percentile(scores, threshold_percentile).
        - This flags only genuinely unusual deviations from the rolling median.

    To override auto-calibration, set ``threshold_mad`` explicitly in the config.
    """

    def __init__(self, config: MADDetectorConfig) -> None:
        self.config = config
        self._win_size: int = config.win_size
        self._threshold: float | None = None
        # Last win_size training samples per feature — used to seed test-set scoring
        self._seed_window: np.ndarray | None = None  # shape (win_size, n_features)
        self._columns: list[str] = []
        self._n_samples: int = 0

    # ------------------------------------------------------------------
    # Fit
    # ------------------------------------------------------------------

    def fit(self, dataset: Dataset) -> None:
        """Run through training data and auto-calibrate threshold."""
        X = dataset.samples.astype(np.float64)
        n, n_features = X.shape
        self._columns = list(dataset.columns)
        self._n_samples = n

        # Save the last win_size training samples for continuity in score()
        seed_start = max(0, n - self._win_size)
        self._seed_window = X[seed_start:].copy()  # shape (≤win_size, n_features)

        all_scores: list[float] = []
        for feat_idx in range(n_features):
            col_scores = _rolling_scores(X[:, feat_idx], self._win_size)
            # Only collect non-warm-up scores for threshold calibration
            all_scores.extend(float(s) for s in col_scores[self._win_size:])

        if self.config.threshold_mad is not None:
            self._threshold = self.config.threshold_mad
        else:
            arr = np.array(all_scores, dtype=np.float64)
            if len(arr) == 0 or arr.max() < 1e-9:
                # Constant signal — use default threshold
                self._threshold = 3.5
            else:
                self._threshold = float(np.percentile(arr, self.config.threshold_percentile))
                if self._threshold < 1e-9:
                    self._threshold = 3.5

    # ------------------------------------------------------------------
    # Score / predict
    # ------------------------------------------------------------------

    def _check_fitted(self) -> None:
        if self._threshold is None:
            raise RuntimeError("MADDetector must be fitted before scoring.")

    def score(self, dataset: Dataset) -> np.ndarray:
        """Return max MAD score across features for each sample.

        Scoring continues from the post-fit ring buffer state so that
        test-set scores reflect real sequential behaviour (no look-ahead).
        """
        self._check_fitted()
        X = dataset.samples.astype(np.float64)
        n, n_features = X.shape

        combined = np.zeros(n, dtype=np.float64)
        for feat_idx in range(n_features):
            seed = (
                self._seed_window[:, feat_idx]
                if self._seed_window is not None
                else None
            )
            col_scores = _rolling_scores(X[:, feat_idx], self._win_size, seed=seed)
            np.maximum(combined, col_scores, out=combined)

        return combined.astype(np.float32)

    def predict(self, dataset: Dataset) -> DetectionResult:
        scores = self.score(dataset)
        labels = (scores >= self._threshold).astype(np.int8)
        return DetectionResult(
            scores=scores,
            labels=labels,
            threshold=self._threshold,
            detector_name="mad",
        )

    # ------------------------------------------------------------------
    # Export — fovet_mad_config.h + mad_config.json
    # ------------------------------------------------------------------

    def export(self, output_dir: Path, stem: str, **_kwargs) -> list[Path]:
        """Write fovet_mad_config.h and mad_config.json."""
        self._check_fitted()
        output_dir.mkdir(parents=True, exist_ok=True)

        paths: list[Path] = []

        # C header
        contexts = []
        n_features = len(self._columns)
        seed = self._seed_window  # shape (≤win_size, n_features)

        for feat_idx, col in enumerate(self._columns):
            safe_col = col.replace(" ", "_").replace("-", "_")

            # Build the window[] array for the C struct.
            # The seed window holds up to win_size samples; we pad to
            # FOVET_MAD_MAX_WINDOW with 0.0f.  head=0, count=win_size means
            # the oldest sample is at index 0, newest at index win_size-1.
            window_vals: list[float] = []
            if seed is not None and seed.shape[0] > 0:
                col_seed = seed[:, feat_idx] if n_features > 1 else seed[:, 0]
                # Ensure exactly win_size entries (take last win_size if longer)
                col_seed = col_seed[-self._win_size:]
                window_vals = [float(v) for v in col_seed]

            # Pad to FOVET_MAD_MAX_WINDOW
            window_vals += [0.0] * (_FOVET_MAD_MAX_WINDOW - len(window_vals))

            window_str = ", ".join(f"{v:.6f}f" for v in window_vals)

            contexts.append(
                _CONTEXT_TEMPLATE.format(
                    column=col,
                    safe_col=safe_col,
                    win_size=self._win_size,
                    threshold=self._threshold,
                    window_values=window_str,
                )
            )

        header = _C_HEADER_TEMPLATE.format(
            pipeline_name=stem,
            n_samples=self._n_samples,
            n_features=n_features,
            columns=", ".join(self._columns),
            win_size=self._win_size,
            threshold=self._threshold,
            threshold_percentile=self.config.threshold_percentile,
            contexts="\n\n".join(contexts),
        )

        h_path = output_dir / "fovet_mad_config.h"
        h_path.write_text(header, encoding="utf-8")
        paths.append(h_path)

        # JSON config
        json_data = {
            "pipeline": stem,
            "detector": "mad",
            "win_size": self._win_size,
            "threshold_mad": self._threshold,
            "threshold_percentile": self.config.threshold_percentile,
            "features": self._columns,
            "n_training_samples": self._n_samples,
        }

        j_path = output_dir / "mad_config.json"
        j_path.write_text(json.dumps(json_data, indent=2), encoding="utf-8")
        paths.append(j_path)

        return paths
