"""
Z-Score detector -- Welford online algorithm.

Mirrors the FovetZScore struct in edge-core/include/fovet/zscore.h so that
calibrated parameters can be exported and loaded directly on the ESP32.

Per-feature statistics are computed independently.
Anomaly score = max |z-score| across all features.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from forge.config import ZScoreDetectorConfig
from forge.data.base import Dataset
from forge.detectors.base import Detector, DetectionResult

# Mirrors SDK header comment
_C_HEADER_TEMPLATE = """\
/*
 * Fovet SDK -- Sentinelle
 * Auto-generated by Fovet Forge. DO NOT EDIT.
 *
 * Z-Score calibration for pipeline: {pipeline_name}
 * Calibrated on {n_samples} samples, {n_features} feature(s): {columns}
 * Threshold: {threshold_sigma}sigma
 */
#ifndef FOVET_ZSCORE_CONFIG_H
#define FOVET_ZSCORE_CONFIG_H

#include "fovet/zscore.h"

/* One FovetZScore context per feature channel.
 * Pass the matching struct to fovet_zscore_update() in your HAL loop. */
{contexts}
#endif /* FOVET_ZSCORE_CONFIG_H */
"""

_CONTEXT_TEMPLATE = """\
/* Feature: {column} -- mean={mean:.6f}, stddev={stddev:.6f} */
static FovetZScore fovet_zscore_{safe_col} = {{
    .count            = {count}U,
    .mean             = {mean:.6f}f,
    .M2               = {M2:.6f}f,
    .threshold_sigma  = {threshold:.6f}f,
    .min_samples      = 0U,   /* pre-calibrated: detection active from first sample */
    .window_size      = 0U,   /* infinite window: Forge pre-calibrates on clean data */
}};"""


class ZScoreDetector(Detector):
    """Welford online Z-Score anomaly detector.

    Fits per-feature statistics on a training dataset, then scores new
    samples by their max absolute z-score across features.
    """

    def __init__(self, config: ZScoreDetectorConfig) -> None:
        self.config = config
        # Per-feature Welford state (set after fit)
        self._count: int = 0
        self._mean: np.ndarray | None = None   # shape (n_features,)
        self._M2: np.ndarray | None = None     # shape (n_features,)
        self._columns: list[str] = []

    # ------------------------------------------------------------------
    # Welford online update (vectorised across features)
    # ------------------------------------------------------------------

    def fit(self, dataset: Dataset) -> None:
        """Compute per-feature mean and variance via Welford's algorithm."""
        X = dataset.samples.astype(np.float64)
        n, n_features = X.shape

        count = 0
        mean = np.zeros(n_features)
        M2 = np.zeros(n_features)

        for i in range(n):
            count += 1
            delta = X[i] - mean
            mean += delta / count
            delta2 = X[i] - mean
            M2 += delta * delta2

        self._count = count
        self._mean = mean
        self._M2 = M2
        self._columns = list(dataset.columns)

    def _check_fitted(self) -> None:
        if self._mean is None:
            raise RuntimeError("ZScoreDetector must be fitted before scoring.")

    def score(self, dataset: Dataset) -> np.ndarray:
        """Return max |z-score| across features for each sample."""
        self._check_fitted()
        X = dataset.samples.astype(np.float64)
        stddev = self._stddev()
        z = np.abs(X - self._mean) / (stddev + 1e-9)  # (n, n_features)
        return z.max(axis=1).astype(np.float32)        # (n,)

    def predict(self, dataset: Dataset) -> DetectionResult:
        scores = self.score(dataset)
        threshold = float(self.config.threshold_sigma)
        labels = (scores >= threshold).astype(np.int8)
        return DetectionResult(
            scores=scores,
            labels=labels,
            threshold=threshold,
            detector_name="zscore",
        )

    # ------------------------------------------------------------------
    # Export -- generates fovet_zscore_config.h for the SDK
    # ------------------------------------------------------------------

    def export(self, output_dir: Path, stem: str, **_kwargs) -> list[Path]:
        """Write fovet_zscore_config.h pre-loaded with calibrated parameters."""
        self._check_fitted()
        output_dir.mkdir(parents=True, exist_ok=True)

        stddev = self._stddev()
        contexts = []
        for i, col in enumerate(self._columns):
            safe_col = col.replace(" ", "_").replace("-", "_")
            contexts.append(_CONTEXT_TEMPLATE.format(
                column=col,
                safe_col=safe_col,
                count=self._count,
                mean=float(self._mean[i]),
                stddev=float(stddev[i]),
                M2=float(self._M2[i]),
                threshold=self.config.threshold_sigma,
            ))

        header = _C_HEADER_TEMPLATE.format(
            pipeline_name=stem,
            n_samples=self._count,
            n_features=len(self._columns),
            columns=", ".join(self._columns),
            threshold_sigma=self.config.threshold_sigma,
            contexts="\n\n".join(contexts),
        )

        out_path = output_dir / "fovet_zscore_config.h"
        out_path.write_text(header, encoding="utf-8")
        return [out_path]

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _stddev(self) -> np.ndarray:
        if self._count < 2:
            return np.ones_like(self._mean)
        return np.sqrt(self._M2 / (self._count - 1))

    @property
    def mean(self) -> np.ndarray:
        self._check_fitted()
        return self._mean.copy()

    @property
    def stddev(self) -> np.ndarray:
        self._check_fitted()
        return self._stddev().copy()
