"""
Fovet Forge — deploy.py

Deploy a .tflite model to an ESP32 PlatformIO project.

Workflow:
  1. Read .tflite file
  2. Generate C source (alignas(16) byte array) → model_data.cpp
  3. Copy model_data.cpp into the target PlatformIO project
  4. Run ``pio run`` to compile
  5. Run ``pio run --target upload`` to flash (unless --compile-only)

Built-in targets:
  person_detection  →  edge-core/examples/esp32/person_detection/
  fire_detection    →  edge-core/examples/esp32/fire_detection/
  zscore_demo       →  edge-core/examples/esp32/zscore_demo/

Usage (CLI):
    forge deploy --model model.tflite --target person_detection
    forge deploy --model model.tflite --target person_detection --compile-only
    forge deploy --model custom.tflite --target person_detection --port COM5

Usage (module):
    from forge.deploy import deploy, generate_model_cpp
"""

from __future__ import annotations

import subprocess
from pathlib import Path

# ---------------------------------------------------------------------------
# Built-in target registry
# Maps target name → (project dir relative to repo root, cpp path, array name)
# ---------------------------------------------------------------------------
_BUILTIN_TARGETS: dict[str, tuple[str, str, str]] = {
    "person_detection": (
        "edge-core/examples/esp32/person_detection",
        "src/model_data.cpp",
        "g_person_detect_model_data",
    ),
    "fire_detection": (
        "edge-core/examples/esp32/fire_detection",
        "src/model_data.cpp",
        "g_fire_model_data",
    ),
    "zscore_demo": (
        "edge-core/examples/esp32/zscore_demo",
        "src/model_data.cpp",
        "g_model_data",
    ),
}


def _find_repo_root() -> Path:
    """Walk up from this file to find the fovet monorepo root.

    Identifies the root as the first ancestor directory containing ``edge-core/``.
    """
    # src/forge/deploy.py → src/forge/ → src/ → automl-pipeline/ → fovet/ (root)
    candidate = Path(__file__).resolve()
    for _ in range(8):
        candidate = candidate.parent
        if (candidate / "edge-core").exists():
            return candidate
    # Fallback: 4 levels up
    return Path(__file__).resolve().parent.parent.parent.parent


def generate_model_cpp(
    tflite_path: Path,
    array_name: str = "g_model_data",
) -> str:
    """Generate a C++ source file embedding .tflite bytes as a ``uint8_t`` array.

    The output follows the same format as the TFLite Micro examples:
    ``alignas(16)`` for CMSIS compatibility, ``const int`` length variable.

    Args:
        tflite_path: Path to the .tflite model file.
        array_name:  C identifier for the data array.
                     The length variable is named ``<array_name>_len``.

    Returns:
        C++ source file content as a string.
    """
    tflite_bytes = tflite_path.read_bytes()
    length_name = f"{array_name}_len"
    model_size = len(tflite_bytes)

    # Format bytes as hex, 12 per line (matches person_detect_model_data.cpp style)
    chunks = [f"0x{b:02x}" for b in tflite_bytes]
    rows: list[str] = []
    for i in range(0, len(chunks), 12):
        rows.append("    " + ", ".join(chunks[i : i + 12]) + ",")
    if rows:
        rows[-1] = rows[-1].rstrip(",")

    hex_body = "\n".join(rows)

    return (
        "/*\n"
        " * Fovet SDK \u2014 Sentinelle\n"
        " * Copyright (C) 2026 Antoine Porte. All rights reserved.\n"
        " * LGPL v3 for non-commercial use.\n"
        " * Commercial licensing: contact@fovet.eu\n"
        " *\n"
        " * Auto-generated by Fovet Forge deploy.py \u2014 do not edit manually.\n"
        f" * Source : {tflite_path.name}  ({model_size} bytes / "
        f"{model_size / 1024:.1f} KB)\n"
        " *\n"
        " * This is a TensorFlow Lite model file that has been converted into a\n"
        " * C data array for devices that don\u2019t have a file system.\n"
        " */\n\n"
        "#include <stdint.h>\n\n"
        "// Keep aligned to 16 bytes for CMSIS\n"
        f"alignas(16) const unsigned char {array_name}[] = {{\n"
        f"{hex_body}\n"
        "};\n\n"
        f"const int {length_name} = {model_size};\n"
    )


def deploy(
    tflite_path: Path,
    target: str,
    port: str = "COM4",
    compile_only: bool = False,
    custom_project_dir: Path | None = None,
) -> None:
    """Deploy a .tflite model to an ESP32 via PlatformIO.

    Steps:
      1. Generate ``model_data.cpp`` from *tflite_path*.
      2. Write it into the PlatformIO project for *target*.
      3. Run ``pio run`` to compile.
      4. Optionally run ``pio run --target upload`` to flash.

    Args:
        tflite_path:        Path to the .tflite model file.
        target:             Built-in target name or custom env name when
                            *custom_project_dir* is provided.
        port:               Serial port for flashing (default: ``COM4``).
        compile_only:       Skip the upload step if ``True``.
        custom_project_dir: Override project directory. When set, *target* is
                            used as the PlatformIO environment name (``-e``).

    Raises:
        FileNotFoundError: If *tflite_path* or resolved project directory does
                           not exist.
        ValueError:        If *target* is not a known built-in and no
                           *custom_project_dir* is provided.
        RuntimeError:      If ``pio run`` exits with a non-zero code.
    """
    if not tflite_path.exists():
        raise FileNotFoundError(f"TFLite model not found: {tflite_path}")

    # ------------------------------------------------------------------
    # Resolve project directory and C identifiers
    # ------------------------------------------------------------------
    if custom_project_dir is not None:
        project_dir = custom_project_dir
        cpp_rel = "src/model_data.cpp"
        array_name = "g_model_data"
        env_name = target
    elif target in _BUILTIN_TARGETS:
        repo_root = _find_repo_root()
        rel_project, cpp_rel, array_name = _BUILTIN_TARGETS[target]
        project_dir = repo_root / rel_project
        env_name = target
    else:
        known = ", ".join(sorted(_BUILTIN_TARGETS))
        raise ValueError(
            f"Unknown target: {target!r}. Built-in targets: {known}. "
            "Pass --project-dir to specify a custom PlatformIO project."
        )

    if not project_dir.exists():
        raise FileNotFoundError(
            f"PlatformIO project directory not found: {project_dir}"
        )

    cpp_path = project_dir / cpp_rel

    # ------------------------------------------------------------------
    # Generate and write model_data.cpp
    # ------------------------------------------------------------------
    cpp_content = generate_model_cpp(tflite_path, array_name)
    cpp_path.parent.mkdir(parents=True, exist_ok=True)
    cpp_path.write_text(cpp_content, encoding="utf-8")
    print(f"  Written : {cpp_path}  ({len(tflite_path.read_bytes())} bytes)")

    # ------------------------------------------------------------------
    # Compile with PlatformIO
    # ------------------------------------------------------------------
    print(f"\n--- PlatformIO compile ({env_name}) ---")
    _run_pio(["pio", "run", "-d", str(project_dir), "-e", env_name])

    if compile_only:
        print("\nCompile-only mode \u2014 skipping flash.")
        return

    # ------------------------------------------------------------------
    # Flash
    # ------------------------------------------------------------------
    print(f"\n--- PlatformIO upload \u2192 {port} ---")
    _run_pio([
        "pio", "run",
        "-d", str(project_dir),
        "-e", env_name,
        "--target", "upload",
        "--upload-port", port,
    ])
    print(f"\nFlash complete. Monitor: pio device monitor -d {project_dir} -e {env_name}")


def _run_pio(cmd: list[str]) -> None:
    """Run a PlatformIO command, raising RuntimeError on failure."""
    result = subprocess.run(cmd, check=False)
    if result.returncode != 0:
        raise RuntimeError(
            f"Command failed (exit {result.returncode}): {' '.join(cmd)}"
        )


# ---------------------------------------------------------------------------
# Standalone entry point
# ---------------------------------------------------------------------------

def _main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "Fovet Forge \u2014 deploy a TFLite model to an ESP32 via PlatformIO.\n"
            f"Built-in targets: {', '.join(sorted(_BUILTIN_TARGETS))}"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--model", "-m", required=True,
        help="Path to .tflite model file",
    )
    parser.add_argument(
        "--target", "-t", default="person_detection",
        help="Built-in target name or PlatformIO env name (default: person_detection)",
    )
    parser.add_argument(
        "--port", "-p", default="COM4",
        help="Upload serial port (default: COM4)",
    )
    parser.add_argument(
        "--compile-only", action="store_true",
        help="Compile only, do not flash",
    )
    parser.add_argument(
        "--project-dir",
        help="Custom PlatformIO project directory (overrides built-in target path)",
    )
    args = parser.parse_args()

    tflite_path = Path(args.model)
    custom_dir = Path(args.project_dir) if args.project_dir else None

    try:
        deploy(
            tflite_path=tflite_path,
            target=args.target,
            port=args.port,
            compile_only=args.compile_only,
            custom_project_dir=custom_dir,
        )
    except (FileNotFoundError, ValueError, RuntimeError) as exc:
        print(f"Error: {exc}", flush=True)
        raise SystemExit(1) from exc


if __name__ == "__main__":
    _main()
