"""
Manifest exporter — generates fovet_model_manifest.h for Sentinelle firmware.

The manifest is a C header that embeds pipeline metadata (sensor type, unit,
value range, labels) into the firmware at compile time.  The firmware uses
these constants in the MQTT canonical payload so Vigie can auto-scale charts
and display the correct unit without any hardcoded logic.

Workflow:
  1. Run Forge → models/<pipeline>/ contains fovet_model_manifest.h
  2. Copy fovet_model_manifest.h into PlatformIO project src/
  3. Firmware #include "fovet_model_manifest.h"
  4. MQTT payload includes model_id, unit, value_min, value_max from macros
  5. Vigie reads those fields and auto-scales chart + shows unit
"""

from __future__ import annotations

from pathlib import Path

from forge.config import PipelineConfig


_MANIFEST_TEMPLATE = """\
/*
 * Fovet SDK — Sentinelle
 * Auto-generated by Fovet Forge. DO NOT EDIT.
 * Copy to your PlatformIO project src/ directory.
 *
 * Pipeline : {pipeline_name}
 * Generated: by `uv run forge run --config <your_config.yaml>`
 */
#ifndef FOVET_MODEL_MANIFEST_H
#define FOVET_MODEL_MANIFEST_H

/* Unique model identifier — matches Forge pipeline name.
 * Published as "model_id" in every MQTT canonical payload. */
#define FOVET_MODEL_ID           "{model_id}"

/* Sensor type — used by Vigie for routing and display.
 * Values: "synthetic" | "imu" | "camera" | "temperature" | "hr" | "unknown" */
#define FOVET_MODEL_SENSOR       "{sensor}"

/* Primary value unit — displayed on Vigie chart Y-axis.
 * Values: "z_score" | "g" | "score" | "bpm" | "C" | "r_mean" | "value" */
#define FOVET_MODEL_UNIT         "{unit}"

/* Expected value range — Vigie uses these to auto-scale the chart Y-axis.
 * Set to the physical range of the sensor/score, not the anomaly threshold. */
#define FOVET_MODEL_VALUE_MIN    ({value_min:.4f}f)
#define FOVET_MODEL_VALUE_MAX    ({value_max:.4f}f)

/* Human-readable labels published to Vigie via MQTT "label" field. */
#define FOVET_MODEL_LABEL_NORMAL  "{label_normal}"
#define FOVET_MODEL_LABEL_ANOMALY "{label_anomaly}"

#endif /* FOVET_MODEL_MANIFEST_H */
"""


def export_manifest(
    config: PipelineConfig,
    output_dir: Path,
    value_min: float | None = None,
    value_max: float | None = None,
) -> Path:
    """Write fovet_model_manifest.h to *output_dir*.

    ``value_min`` / ``value_max`` override ``config.manifest.value_min/max``.
    This lets the pipeline pass auto-computed percentile bounds when the YAML
    leaves those fields unset (None).

    Returns the path of the written file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    m = config.manifest

    resolved_min = value_min if value_min is not None else (m.value_min if m.value_min is not None else -10.0)
    resolved_max = value_max if value_max is not None else (m.value_max if m.value_max is not None else  10.0)

    content = _MANIFEST_TEMPLATE.format(
        pipeline_name=config.name,
        model_id=config.name,
        sensor=m.sensor,
        unit=m.unit,
        value_min=resolved_min,
        value_max=resolved_max,
        label_normal=m.label_normal,
        label_anomaly=m.label_anomaly,
    )

    out = output_dir / "fovet_model_manifest.h"
    out.write_text(content, encoding="utf-8")
    return out
