"""
Feature normalization — StandardScaler wrapper for Fovet Forge pipelines.

The scaler is fit on training data ONLY, then applied to both train and test
datasets. Fitted parameters are exported so that firmware/gateway code can
apply the same transformation before inference.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from forge.data.base import Dataset


class Scaler:
    """StandardScaler (zero-mean, unit-variance) for Forge datasets.

    Fit on training data, apply to both train and test.
    Stores mean_ and scale_ per feature for export.
    """

    def __init__(self) -> None:
        self.mean_: np.ndarray | None = None    # shape (n_features,)
        self.scale_: np.ndarray | None = None   # shape (n_features,)
        self.columns_: list[str] = []

    def fit(self, dataset: Dataset) -> None:
        """Compute per-feature mean and std from training data."""
        X = dataset.samples.astype(np.float64)
        self.mean_ = X.mean(axis=0)
        std = X.std(axis=0, ddof=1)  # sample std (ddof=1)
        # Avoid division by zero for constant features
        self.scale_ = np.where(std > 1e-9, std, 1.0)
        self.columns_ = list(dataset.columns)

    def transform(self, dataset: Dataset) -> Dataset:
        """Apply (x - mean) / scale to each feature column."""
        if self.mean_ is None:
            raise RuntimeError("Scaler must be fitted before transform.")
        X = dataset.samples.astype(np.float32)
        X_norm = (X - self.mean_.astype(np.float32)) / self.scale_.astype(np.float32)
        return Dataset(
            samples=X_norm,
            columns=dataset.columns,
            labels=dataset.labels,
        )

    def fit_transform(self, dataset: Dataset) -> Dataset:
        """Fit on dataset then return transformed version."""
        self.fit(dataset)
        return self.transform(dataset)

    def export(self, output_dir: Path, stem: str) -> Path:
        """Write scaler parameters as JSON for documentation and firmware use.

        The exported file contains per-feature mean and scale so that
        firmware can apply: normalized = (raw - mean) / scale
        """
        if self.mean_ is None:
            raise RuntimeError("Scaler must be fitted before export.")
        output_dir.mkdir(parents=True, exist_ok=True)

        params = {
            "pipeline": stem,
            "normalization": "StandardScaler",
            "formula": "normalized = (raw - mean) / scale",
            "features": self.columns_,
            "mean": [round(float(v), 8) for v in self.mean_],
            "scale": [round(float(v), 8) for v in self.scale_],
            "note": (
                "Apply this normalization to each sensor reading before "
                "passing to the detector. mean and scale are per-feature."
            ),
        }

        out_path = output_dir / "scaler_params.json"
        out_path.write_text(json.dumps(params, indent=2), encoding="utf-8")
        return out_path

    def export_c_header(self, output_dir: Path, stem: str) -> Path:
        """Write fovet_scaler_params.h with static arrays for firmware normalization.

        The generated header is ready to include on the ESP32:

            #include "fovet_scaler_params.h"
            // Apply: normalized[i] = (raw[i] - fovet_scaler_mean[i]) / fovet_scaler_scale[i]
        """
        if self.mean_ is None:
            raise RuntimeError("Scaler must be fitted before export.")
        output_dir.mkdir(parents=True, exist_ok=True)

        n = len(self.mean_)
        mean_vals  = ", ".join(f"{float(v):.6f}f" for v in self.mean_)
        scale_vals = ", ".join(f"{float(v):.6f}f" for v in self.scale_)
        col_names  = ", ".join(self.columns_)

        header = (
            "/*\n"
            " * Fovet SDK — Sentinelle\n"
            " * Auto-generated by Fovet Forge. DO NOT EDIT.\n"
            " *\n"
            f" * StandardScaler parameters for pipeline: {stem}\n"
            f" * Features ({n}): {col_names}\n"
            " * Formula: normalized[i] = (raw[i] - mean[i]) / scale[i]\n"
            " */\n"
            "#ifndef FOVET_SCALER_PARAMS_H\n"
            "#define FOVET_SCALER_PARAMS_H\n"
            "\n"
            f"#define FOVET_SCALER_N_FEATURES {n}\n"
            "\n"
            "/* Per-feature mean (subtract from raw reading) */\n"
            f"static const float fovet_scaler_mean[{n}]  = {{ {mean_vals} }};\n"
            "\n"
            "/* Per-feature scale (divide after subtracting mean) */\n"
            f"static const float fovet_scaler_scale[{n}] = {{ {scale_vals} }};\n"
            "\n"
            "#endif /* FOVET_SCALER_PARAMS_H */\n"
        )

        out_path = output_dir / "fovet_scaler_params.h"
        out_path.write_text(header, encoding="utf-8")
        return out_path
