/*
 * Fovet SDK — Sentinelle
 * Default model manifest for zscore_demo.
 * Auto-generated by Fovet Forge — or edit manually.
 *
 * To regenerate from Forge:
 *   uv run forge run --config automl-pipeline/configs/demo_zscore.yaml
 *   cp automl-pipeline/models/demo_zscore/fovet_model_manifest.h \
 *      edge-core/examples/esp32/zscore_demo/src/
 */
#ifndef FOVET_MODEL_MANIFEST_H
#define FOVET_MODEL_MANIFEST_H

#define FOVET_MODEL_ID            "demo-zscore-sine"
#define FOVET_MODEL_SENSOR        "synthetic"
#define FOVET_MODEL_UNIT          "z_score"
#define FOVET_MODEL_VALUE_MIN     (-6.0f)
#define FOVET_MODEL_VALUE_MAX     (6.0f)
#define FOVET_MODEL_LABEL_NORMAL  "normal"
#define FOVET_MODEL_LABEL_ANOMALY "anomaly"

#endif /* FOVET_MODEL_MANIFEST_H */
