/*
 * Ardent SDK — Pulse
 * Default model manifest for zscore_demo.
 * Auto-generated by Ardent Forge — or edit manually.
 *
 * To regenerate from Forge:
 *   uv run forge run --config automl-pipeline/configs/demo_zscore.yaml
 *   cp automl-pipeline/models/demo_zscore/ard_model_manifest.h \
 *      edge-core/examples/esp32/zscore_demo/src/
 */
#ifndef ARD_MODEL_MANIFEST_H
#define ARD_MODEL_MANIFEST_H

#define ARD_MODEL_ID            "demo-zscore-sine"
#define ARD_MODEL_SENSOR        "synthetic"
#define ARD_MODEL_UNIT          "z_score"
#define ARD_MODEL_VALUE_MIN     (-6.0f)
#define ARD_MODEL_VALUE_MAX     (6.0f)
#define ARD_MODEL_LABEL_NORMAL  "normal"
#define ARD_MODEL_LABEL_ANOMALY "anomaly"

#endif /* ARD_MODEL_MANIFEST_H */
