/*
 * Fovet SDK -- Sentinelle
 * Auto-generated by Fovet Forge. DO NOT EDIT.
 *
 * Z-Score calibration for pipeline: demo-zscore-sine
 * Calibrated on 1000 samples, 1 feature(s): value
 * Threshold: 3.0sigma
 */
#ifndef FOVET_ZSCORE_CONFIG_H
#define FOVET_ZSCORE_CONFIG_H

#include "fovet/zscore.h"

/* One FovetZScore context per feature channel.
 * Pass the matching struct to fovet_zscore_update() in your HAL loop. */
/* Feature: value -- mean=-0.031523, stddev=1.065106 */
static FovetZScore fovet_zscore_value = {
    .count            = 1000U,
    .mean             = -0.031523f,
    .M2               = 1133.315717f,
    .threshold_sigma  = 3.000000f,
    .min_samples      = 0U,   /* pre-calibrated: detection active from first sample */
    .window_size      = 0U,   /* infinite window: Forge pre-calibrates on clean data */
};
#endif /* FOVET_ZSCORE_CONFIG_H */
