/*
 * Ardent SDK -- Pulse
 * Auto-generated by Ardent Forge. DO NOT EDIT.
 *
 * Z-Score calibration for pipeline: demo-zscore-sine
 * Calibrated on 800 samples, 1 feature(s): value
 * Threshold: 3.0sigma
 */
#ifndef ARD_ZSCORE_CONFIG_H
#define ARD_ZSCORE_CONFIG_H

#include "ardent/zscore.h"

/* One ArdentZScore context per feature channel.
 * Pass the matching struct to ard_zscore_update() in your HAL loop. */
/* Feature: value -- mean=-0.042213, stddev=1.071779 */
static ArdentZScore ard_zscore_value = {
    .count            = 800U,
    .mean             = -0.042213f,
    .M2               = 917.819732f,
    .threshold_sigma  = 3.000000f,
    .min_samples      = 0U,   /* pre-calibrated: detection active from first sample */
    .window_size      = 0U,   /* infinite window: Forge pre-calibrates on clean data */
};
#endif /* ARD_ZSCORE_CONFIG_H */
