/*
 * Ardent SDK — Pulse
 * Auto-generated by Ardent Forge. DO NOT EDIT.
 * Copy to your PlatformIO project src/ directory.
 *
 * Pipeline : imu-zscore-mpu6050
 * Generated: default manifest — regenerate with `uv run forge run --config configs/imu_zscore.yaml`
 */
#ifndef ARD_MODEL_MANIFEST_H
#define ARD_MODEL_MANIFEST_H

/* Unique model identifier — matches Cast pipeline name.
 * Published as "model_id" in every MQTT canonical payload. */
#define ARD_MODEL_ID           "imu-zscore-mpu6050"

/* Sensor type — used by Watch for routing and display. */
#define ARD_MODEL_SENSOR       "imu"

/* Primary value unit — displayed on Watch chart Y-axis. */
#define ARD_MODEL_UNIT         "g"

/* Expected value range — Watch uses these to auto-scale the chart Y-axis.
 * Magnitude at rest ≈ 1g. Hard fall can reach 4–6g. */
#define ARD_MODEL_VALUE_MIN    (0.0000f)
#define ARD_MODEL_VALUE_MAX    (4.0000f)

/* Human-readable labels published to Watch via MQTT "label" field. */
#define ARD_MODEL_LABEL_NORMAL  "normal"
#define ARD_MODEL_LABEL_ANOMALY "anomaly"

#endif /* ARD_MODEL_MANIFEST_H */
