/*
 * Fovet SDK — Sentinelle
 * Auto-generated by Fovet Forge. DO NOT EDIT.
 * Copy to your PlatformIO project src/ directory.
 *
 * Pipeline : imu-zscore-mpu6050
 * Generated: default manifest — regenerate with `uv run forge run --config configs/imu_zscore.yaml`
 */
#ifndef FOVET_MODEL_MANIFEST_H
#define FOVET_MODEL_MANIFEST_H

/* Unique model identifier — matches Forge pipeline name.
 * Published as "model_id" in every MQTT canonical payload. */
#define FOVET_MODEL_ID           "imu-zscore-mpu6050"

/* Sensor type — used by Vigie for routing and display. */
#define FOVET_MODEL_SENSOR       "imu"

/* Primary value unit — displayed on Vigie chart Y-axis. */
#define FOVET_MODEL_UNIT         "g"

/* Expected value range — Vigie uses these to auto-scale the chart Y-axis.
 * Magnitude at rest ≈ 1g. Hard fall can reach 4–6g. */
#define FOVET_MODEL_VALUE_MIN    (0.0000f)
#define FOVET_MODEL_VALUE_MAX    (4.0000f)

/* Human-readable labels published to Vigie via MQTT "label" field. */
#define FOVET_MODEL_LABEL_NORMAL  "normal"
#define FOVET_MODEL_LABEL_ANOMALY "anomaly"

#endif /* FOVET_MODEL_MANIFEST_H */
