/*
 * Ardent SDK — Pulse
 * Default model manifest for fire_detection.
 * Auto-generated by Ardent Forge — or edit manually.
 *
 * To regenerate from Forge:
 *   uv run forge run --config automl-pipeline/configs/fire_detection.yaml
 *   cp automl-pipeline/models/fire_detection/ard_model_manifest.h \
 *      edge-core/examples/esp32/fire_detection/src/
 */
#ifndef ARD_MODEL_MANIFEST_H
#define ARD_MODEL_MANIFEST_H

/* R_mean of OV2640 QQVGA RGB565 frame (0–255 range) */
#define ARD_MODEL_ID            "fire-detection"
#define ARD_MODEL_SENSOR        "camera"
#define ARD_MODEL_UNIT          "r_mean"
#define ARD_MODEL_VALUE_MIN     (0.0f)
#define ARD_MODEL_VALUE_MAX     (255.0f)
#define ARD_MODEL_LABEL_NORMAL  "normal"
#define ARD_MODEL_LABEL_ANOMALY "fire"

#endif /* ARD_MODEL_MANIFEST_H */
