/*
 * Fovet SDK — Sentinelle
 * Default model manifest for fire_detection.
 * Auto-generated by Fovet Forge — or edit manually.
 *
 * To regenerate from Forge:
 *   uv run forge run --config automl-pipeline/configs/fire_detection.yaml
 *   cp automl-pipeline/models/fire_detection/fovet_model_manifest.h \
 *      edge-core/examples/esp32/fire_detection/src/
 */
#ifndef FOVET_MODEL_MANIFEST_H
#define FOVET_MODEL_MANIFEST_H

/* R_mean of OV2640 QQVGA RGB565 frame (0–255 range) */
#define FOVET_MODEL_ID            "fire-detection"
#define FOVET_MODEL_SENSOR        "camera"
#define FOVET_MODEL_UNIT          "r_mean"
#define FOVET_MODEL_VALUE_MIN     (0.0f)
#define FOVET_MODEL_VALUE_MAX     (255.0f)
#define FOVET_MODEL_LABEL_NORMAL  "normal"
#define FOVET_MODEL_LABEL_ANOMALY "fire"

#endif /* FOVET_MODEL_MANIFEST_H */
