/*
 * Fovet SDK — Sentinelle
 * Copyright (C) 2026 Antoine Porte. All rights reserved.
 * LGPL v3 for non-commercial use.
 * Commercial licensing: contact@fovet.eu
 */
"use client";

import { useEffect, useState, useCallback } from "react";
import { apiFetch } from "@/lib/api-client";
import {
  ResponsiveContainer,
  LineChart,
  Line,
  YAxis,
  ReferenceLine,
  Tooltip,
} from "recharts";

/* -------------------------------------------------------------------------
 * Thresholds — must match fovet/profiles/temp_profile.h (H3.3)
 * and thermal_thresholds.h generated by ThermalStressPipeline (H3.2)
 * ------------------------------------------------------------------------- */
const WBGT_WARN_C   = 25;   /* WBGT ≥ this → WARN   */
const WBGT_DANGER_C = 28;   /* WBGT ≥ this → DANGER  */
const COLD_ALERT_C  = 10;   /* T ≤ this   → COLD    */
const EMA_ALPHA     = 0.10;
const WARMUP_SAMPLES = 10;

export type TempLevel = "UNKNOWN" | "SAFE" | "WARN" | "DANGER" | "COLD";

interface Reading {
  id: string;
  timestamp: string;
  value: number;      /* value_1 = celsius */
  value2?: number;    /* value_2 = humidity_pct */
}

interface Props {
  deviceId: string;
  deviceName: string;
  location: string | null;
  selected?: boolean;
  onSelect: () => void;
}

/* -------------------------------------------------------------------------
 * Stull (2011) indoor WBGT approximation — mirrors C implementation in H3.3
 * ------------------------------------------------------------------------- */
function computeWbgt(celsius: number, humidityPct: number): number {
  const t = celsius;
  const h = humidityPct;
  const nwb =
    t * Math.atan(0.151977 * Math.sqrt(h + 8.313659)) +
    Math.atan(t + h) -
    Math.atan(h - 1.676331) +
    0.00391838 * Math.pow(h, 1.5) * Math.atan(0.023101 * h) -
    4.686035;
  return 0.7 * nwb + 0.3 * t;
}

/** Compute EMA on an ordered array of values. */
function computeEma(values: number[]): number {
  if (values.length === 0) return 0;
  let ema = values[0];
  for (let i = 1; i < values.length; i++) {
    ema = EMA_ALPHA * values[i] + (1 - EMA_ALPHA) * ema;
  }
  return ema;
}

/** Classify thermal level using the same logic as temp_profile.c. */
function classify(emaCelsius: number, humidityPct: number, count: number): TempLevel {
  if (count < WARMUP_SAMPLES) return "UNKNOWN";
  if (emaCelsius <= COLD_ALERT_C)  return "COLD";
  const wbgt = computeWbgt(emaCelsius, humidityPct);
  if (wbgt >= WBGT_DANGER_C) return "DANGER";
  if (wbgt >= WBGT_WARN_C)   return "WARN";
  return "SAFE";
}

const LEVEL_COLORS: Record<TempLevel, string> = {
  UNKNOWN: "text-gray-500",
  SAFE:    "text-green-400",
  WARN:    "text-amber-400",
  DANGER:  "text-red-400",
  COLD:    "text-blue-400",
};

const LEVEL_BORDER: Record<TempLevel, string> = {
  UNKNOWN: "border-gray-800 bg-gray-900",
  SAFE:    "border-gray-800 bg-gray-900",
  WARN:    "border-amber-800/50 bg-amber-950/10",
  DANGER:  "border-red-800/60 bg-red-950/15",
  COLD:    "border-blue-800/50 bg-blue-950/10",
};

const LEVEL_LABEL: Record<TempLevel, string> = {
  UNKNOWN: "En attente",
  SAFE:    "Normal",
  WARN:    "Chaleur ↑",
  DANGER:  "Stress thermique",
  COLD:    "Froid",
};

const LEVEL_DOT: Record<TempLevel, string> = {
  UNKNOWN: "bg-gray-500",
  SAFE:    "bg-green-400",
  WARN:    "bg-amber-400",
  DANGER:  "bg-red-500 animate-pulse",
  COLD:    "bg-blue-400 animate-pulse",
};

const POLL_INTERVAL   = 15_000;
const READINGS_LIMIT  = 100;

export function TempCard({
  deviceId, deviceName, location, selected, onSelect,
}: Props) {
  const [readings, setReadings] = useState<Reading[]>([]);
  const [error, setError]       = useState<string | null>(null);

  const refresh = useCallback(() => {
    apiFetch(`/api/devices/${deviceId}/readings?limit=${READINGS_LIMIT}`)
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<{ data: Reading[] }>;
      })
      .then((env) => {
        setReadings(env.data);
        setError(null);
      })
      .catch((err: unknown) =>
        setError(err instanceof Error ? err.message : "Erreur réseau")
      );
  }, [deviceId]);

  useEffect(() => {
    refresh();
    const id = setInterval(refresh, POLL_INTERVAL);
    return () => clearInterval(id);
  }, [refresh]);

  const celsiusValues  = readings.map((r) => r.value);
  const humidityValues = readings.map((r) => r.value2 ?? 50);
  const emaCelsius     = computeEma(celsiusValues);
  const latestHumidity = humidityValues.at(-1) ?? 50;
  const level          = classify(emaCelsius, latestHumidity, readings.length);
  const latestCelsius  = celsiusValues.at(-1);
  const wbgt           =
    level !== "UNKNOWN" ? computeWbgt(emaCelsius, latestHumidity) : null;

  const chartData = readings.map((r) => ({ celsius: r.value }));

  return (
    <button
      onClick={onSelect}
      className={`w-full text-left rounded-xl border p-4 transition-colors cursor-pointer ${
        selected
          ? "ring-1 ring-blue-500 " + LEVEL_BORDER[level]
          : LEVEL_BORDER[level]
      }`}
    >
      {/* Header */}
      <div className="flex items-start justify-between gap-2 mb-3">
        <div className="min-w-0">
          <p className="font-semibold text-sm text-white truncate">{deviceName}</p>
          {location && (
            <p className="text-xs text-gray-500 truncate mt-0.5">{location}</p>
          )}
        </div>
        <span
          className={`w-2.5 h-2.5 rounded-full shrink-0 mt-1 ${LEVEL_DOT[level]}`}
          title={LEVEL_LABEL[level]}
        />
      </div>

      {/* Level badge + WBGT */}
      <div className="flex items-end justify-between mb-3">
        <div>
          <p className={`text-base font-bold font-mono ${LEVEL_COLORS[level]}`}>
            {LEVEL_LABEL[level]}
          </p>
          {wbgt !== null && (
            <p className="text-xs text-gray-500 mt-0.5">
              WBGT {wbgt.toFixed(1)} °C
            </p>
          )}
        </div>
        {latestCelsius !== undefined && (
          <p className="text-2xl font-bold font-mono text-white leading-none">
            {latestCelsius.toFixed(1)}
            <span className="text-xs text-gray-500 ml-1">°C</span>
          </p>
        )}
      </div>

      {/* Sparkline / warmup progress */}
      {error ? (
        <div className="h-14 flex items-center justify-center text-red-400 text-xs">
          {error}
        </div>
      ) : readings.length === 0 ? (
        <div className="h-14 flex items-center justify-center text-gray-600 text-xs">
          En attente de données…
        </div>
      ) : level === "UNKNOWN" ? (
        <div className="h-14 flex flex-col justify-center gap-1.5 px-0.5">
          <div className="flex justify-between text-xs text-gray-500">
            <span>Initialisation</span>
            <span className="tabular-nums font-mono">{readings.length} / {WARMUP_SAMPLES}</span>
          </div>
          <div className="w-full h-1.5 bg-gray-800 rounded-full overflow-hidden">
            <div
              className="h-full bg-orange-500 rounded-full transition-all duration-500"
              style={{ width: `${Math.min(100, (readings.length / WARMUP_SAMPLES) * 100)}%` }}
            />
          </div>
        </div>
      ) : (
        <ResponsiveContainer width="100%" height={56}>
          <LineChart data={chartData}>
            <YAxis hide domain={[-10, 45]} />
            <ReferenceLine
              y={COLD_ALERT_C}
              stroke="#60a5fa"
              strokeDasharray="3 2"
              strokeWidth={1}
            />
            <Tooltip
              contentStyle={{
                backgroundColor: "#111827",
                border: "1px solid #374151",
                fontSize: 11,
              }}
              labelFormatter={() => ""}
              formatter={(v: unknown) => [
                typeof v === "number" ? `${v.toFixed(1)} °C` : "",
                "Temp.",
              ]}
            />
            <Line
              type="monotone"
              dataKey="celsius"
              stroke="#f97316"
              dot={false}
              strokeWidth={1.5}
              isAnimationActive={false}
            />
          </LineChart>
        </ResponsiveContainer>
      )}

      {/* Threshold legend */}
      <div className="flex items-center gap-3 mt-2">
        <span className="flex items-center gap-1 text-xs text-gray-600">
          <span className="w-3 border-t border-dashed border-blue-400/70" />
          {COLD_ALERT_C} °C
        </span>
        <span className="flex items-center gap-1 text-xs text-gray-600">
          <span className="w-3 border-t border-dashed border-amber-400/70" />
          WBGT {WBGT_WARN_C} °C
        </span>
        <span className="flex items-center gap-1 text-xs text-gray-600">
          <span className="w-3 border-t border-dashed border-red-400/70" />
          WBGT {WBGT_DANGER_C} °C
        </span>
      </div>
    </button>
  );
}
