/*
 * Ardent SDK — Pulse
 * Copyright (C) 2026 Antoine Porte. All rights reserved.
 * LGPL v3 for non-commercial use.
 * Commercial licensing: contact@fovet.eu
 *
 * -------------------------------------------------------------------------
 * temp_profile.h — WBGT-based thermal stress profile (H3.3)
 *
 * Runs at 0.5 Hz consuming the ARD_SOURCE_TEMP biosignal (DHT22).
 * Classifies ambient thermal conditions using the WBGT index (Stull 2011)
 * into four levels:
 *
 *   ARD_TEMP_LEVEL_SAFE    WBGT < wbgt_warn_c   AND T > cold_alert_c
 *   ARD_TEMP_LEVEL_WARN    WBGT ≥ wbgt_warn_c   AND WBGT < wbgt_danger_c
 *   ARD_TEMP_LEVEL_DANGER  WBGT ≥ wbgt_danger_c (heat stress)
 *   ARD_TEMP_LEVEL_COLD    T ≤ cold_alert_c     (cold stress — priority)
 *
 * WBGT (Wet Bulb Globe Temperature — indoor, Stull 2011):
 *   NWB = T × atan(0.151977 × √(H + 8.313659))
 *         + atan(T + H)
 *         − atan(H − 1.676331)
 *         + 0.00391838 × H^1.5 × atan(0.023101 × H)
 *         − 4.686035
 *   WBGT = 0.7 × NWB + 0.3 × T
 *
 * Cold check takes priority — if EMA temperature ≤ cold_alert_c the level
 * is ARD_TEMP_LEVEL_COLD regardless of the WBGT value.
 *
 * Design:
 *   - C99 pure, zero malloc — state lives in ard_temp_ctx_t.
 *   - Hardware access through injected callbacks (LED, alert, sleep).
 *   - TEMP data read via ard_hal_biosignal_read(ARD_SOURCE_TEMP).
 *   - EMA smoothing on temperature (alpha = 0.10 — 10-sample memory at 0.5 Hz).
 *   - Alert callback fired only when level changes (no flood).
 *   - LED callback fired every tick when level is known.
 *   - Default thresholds match thermal_thresholds.h export from H3.2:
 *       wbgt_warn_c = 25.0 °C, wbgt_danger_c = 28.0 °C, cold_alert_c = 10.0 °C
 *     (ISO 7243, moderate physical work)
 *
 * Typical integration:
 *   1. Inject IO:           ard_dht22_set_io(&io)
 *   2. Init DHT22 driver:   ard_dht22_init()
 *   3. Init profile:        ard_temp_init(&ctx, NULL, alert_fn, led_fn, NULL, NULL)
 *   4. Main loop at 0.5 Hz: ard_temp_tick(&ctx)
 * -------------------------------------------------------------------------
 */

#ifndef ARD_TEMP_PROFILE_H
#define ARD_TEMP_PROFILE_H

#include <stdint.h>
#include "ardent/hal/ard_biosignal_hal.h"

#ifdef __cplusplus
extern "C" {
#endif

/* -------------------------------------------------------------------------
 * Default threshold constants
 * These match thermal_thresholds.h generated by ThermalStressPipeline (H3.2).
 * Override via ard_temp_config_t if using custom thresholds.
 * ------------------------------------------------------------------------- */

/** WBGT ≥ this → heat stress warning (°C). */
#define ARD_TEMP_DEFAULT_WBGT_WARN_C    25.0f

/** WBGT ≥ this → heat stress danger (°C). */
#define ARD_TEMP_DEFAULT_WBGT_DANGER_C  28.0f

/** T ≤ this → cold stress alert (°C). */
#define ARD_TEMP_DEFAULT_COLD_ALERT_C   10.0f

/** EMA smoothing factor (α = 0.10 ≈ 10-sample memory at 0.5 Hz). */
#define ARD_TEMP_DEFAULT_EMA_ALPHA      0.10f

/** Samples before first classification (= 10 × 2 s = 20 s warm-up). */
#define ARD_TEMP_DEFAULT_WARMUP         10U

/** Tick period (ms) — DHT22 max sample rate is 0.5 Hz (1 reading every 2 s). */
#define ARD_TEMP_DEFAULT_SLEEP_MS       2000U

/* -------------------------------------------------------------------------
 * Thermal levels
 * ------------------------------------------------------------------------- */

/**
 * @brief Four-level thermal stress classification.
 */
typedef enum {
    ARD_TEMP_LEVEL_UNKNOWN = 0, /**< Warm-up — no classification yet      */
    ARD_TEMP_LEVEL_SAFE    = 1, /**< Normal conditions                     */
    ARD_TEMP_LEVEL_WARN    = 2, /**< Heat stress warning (WBGT ≥ 25 °C)   */
    ARD_TEMP_LEVEL_DANGER  = 3, /**< Heat stress danger  (WBGT ≥ 28 °C)   */
    ARD_TEMP_LEVEL_COLD    = 4  /**< Cold stress alert   (T ≤ 10 °C)      */
} ard_temp_level_t;

/* -------------------------------------------------------------------------
 * Callback types
 * ------------------------------------------------------------------------- */

/**
 * @brief Alert notification callback.
 *
 * Fired when thermal level changes.  Must be fast and non-blocking.
 *
 * @param level      New thermal level.
 * @param user_data  Opaque pointer from ard_temp_init().
 */
typedef void (*ard_temp_alert_fn_t)(ard_temp_level_t level, void *user_data);

/**
 * @brief LED update callback.
 *
 * Called on every tick when level != UNKNOWN.
 * Typical mapping: SAFE→green, WARN→amber, DANGER→red, COLD→blue.
 *
 * @param level  Current thermal level.
 */
typedef void (*ard_temp_led_fn_t)(ard_temp_level_t level);

/**
 * @brief Light-sleep callback (optional).
 *
 * Called at the end of each tick.  NULL = no sleep.
 *
 * @param ms  Requested sleep duration in milliseconds.
 */
typedef void (*ard_temp_sleep_fn_t)(uint32_t ms);

/* -------------------------------------------------------------------------
 * Configuration
 * ------------------------------------------------------------------------- */

/**
 * @brief Thermal profile configuration.
 *
 * Use ard_temp_default_config() to get sensible defaults.
 */
typedef struct {
    float    wbgt_warn_c;            /**< WBGT warn threshold (°C)      (default 25.0) */
    float    wbgt_danger_c;          /**< WBGT danger threshold (°C)    (default 28.0) */
    float    cold_alert_c;           /**< Cold alert threshold (°C)     (default 10.0) */
    float    ema_alpha;              /**< EMA smoothing factor           (default 0.10) */
    uint32_t warmup_samples;         /**< Samples before classifying    (default 10)   */
    uint32_t sleep_between_ticks_ms; /**< Tick sleep duration (ms)      (default 2000) */
} ard_temp_config_t;

/* -------------------------------------------------------------------------
 * Context (opaque — do not access fields directly)
 * ------------------------------------------------------------------------- */

/**
 * @brief Thermal profile runtime context.
 *
 * Zero-initialise before calling ard_temp_init().
 * Size: ≈ 48 bytes on 32-bit platforms.
 */
typedef struct {
    ard_temp_config_t   config;
    ard_temp_alert_fn_t alert_fn;
    ard_temp_led_fn_t   led_fn;
    ard_temp_sleep_fn_t sleep_fn;
    void                 *user_data;

    float              ema_celsius;   /**< Exponential moving average of temperature */
    uint32_t           sample_count;  /**< Total valid TEMP samples received          */
    ard_temp_level_t last_level;    /**< Level at end of previous tick              */
} ard_temp_ctx_t;

/* -------------------------------------------------------------------------
 * Public API
 * ------------------------------------------------------------------------- */

/**
 * @brief Return a ard_temp_config_t pre-filled with sensible defaults.
 *
 * Defaults:
 *   wbgt_warn_c=25.0, wbgt_danger_c=28.0, cold_alert_c=10.0
 *   ema_alpha=0.10, warmup_samples=10, sleep_between_ticks_ms=2000
 */
ard_temp_config_t ard_temp_default_config(void);

/**
 * @brief Compute the indoor WBGT index from dry-bulb temperature and humidity.
 *
 * Uses the Stull (2011) wet-bulb approximation.
 * Valid for T ∈ [0, 40] °C and RH ∈ [5, 99] %.
 *
 * This function is exposed so that callers can pre-compute WBGT before
 * calling ard_temp_tick(), or for direct use in other contexts.
 *
 * @param celsius      Dry-bulb temperature (°C).
 * @param humidity_pct Relative humidity (%).
 *
 * @return WBGT in °C.
 */
float ard_temp_compute_wbgt(float celsius, float humidity_pct);

/**
 * @brief Initialise a thermal profile context.
 *
 * Must be called before ard_temp_tick().
 * ARD_SOURCE_TEMP must already be registered (call ard_dht22_init() first
 * on hardware).
 *
 * @param ctx       Context to initialise.  Must not be NULL.
 * @param cfg       Configuration.  NULL → ard_temp_default_config().
 * @param alert_fn  Level-change callback.  NULL = silent.
 * @param led_fn    LED update callback.    NULL = no LED.
 * @param sleep_fn  Light-sleep callback.   NULL = no sleep.
 * @param user_data Passed through to alert_fn.
 */
void ard_temp_init(ard_temp_ctx_t           *ctx,
                     const ard_temp_config_t  *cfg,
                     ard_temp_alert_fn_t       alert_fn,
                     ard_temp_led_fn_t         led_fn,
                     ard_temp_sleep_fn_t       sleep_fn,
                     void                       *user_data);

/**
 * @brief Run one thermal detection cycle.
 *
 * Sequence:
 *   1. Read TEMP via ard_hal_biosignal_read(ARD_SOURCE_TEMP, &sample).
 *   2. If error (transient — TIMEOUT, CHECKSUM, RANGE): sleep and return 0.
 *   3. Update EMA temperature — seed with first valid sample.
 *   4. Increment sample_count.
 *   5. Classify: UNKNOWN (< warmup) / COLD / WARN / DANGER / SAFE.
 *      Cold check takes priority: ema_celsius ≤ cold_alert_c → COLD.
 *      WBGT is computed from (ema_celsius, raw humidity_pct).
 *   6. If level changed: call alert_fn if not NULL.
 *   7. If level != UNKNOWN: call led_fn if not NULL.
 *   8. If sleep_fn != NULL: call sleep_fn(sleep_between_ticks_ms).
 *
 * @param ctx  Initialised context.  Must not be NULL.
 *
 * @return ARD_HAL_OK (0) on success, transient error, or NODATA.
 *         Negative error only on unexpected biosignal registry failure.
 */
int ard_temp_tick(ard_temp_ctx_t *ctx);

/**
 * @brief Return the current thermal level.
 *
 * @param ctx  Initialised context.
 * @return Current ard_temp_level_t.  UNKNOWN before first classification.
 */
ard_temp_level_t ard_temp_get_level(const ard_temp_ctx_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* ARD_TEMP_PROFILE_H */
