/*
 * Ardent SDK — Pulse
 * Default model manifest for person_detection.
 * Auto-generated by Ardent Forge — or edit manually.
 *
 * To regenerate from Forge (when a custom autoencoder is trained):
 *   uv run forge run --config automl-pipeline/configs/person_detection.yaml
 *   cp automl-pipeline/models/person_detection/ard_model_manifest.h \
 *      edge-core/examples/esp32/person_detection/src/
 */
#ifndef ARD_MODEL_MANIFEST_H
#define ARD_MODEL_MANIFEST_H

/* MobileNetV1 0.25x person detection score (0.0 = no_person, 1.0 = person) */
#define ARD_MODEL_ID            "person-detection"
#define ARD_MODEL_SENSOR        "camera"
#define ARD_MODEL_UNIT          "score"
#define ARD_MODEL_VALUE_MIN     (0.0f)
#define ARD_MODEL_VALUE_MAX     (1.0f)
#define ARD_MODEL_LABEL_NORMAL  "no_person"
#define ARD_MODEL_LABEL_ANOMALY "person"

#endif /* ARD_MODEL_MANIFEST_H */
